from __future__ import annotations


def build_sample_payloads() -> dict[str, dict]:
    base_birth = {
        "date": "2028/04/06",
        "time": "09:33:00",
        "zone": "+00:00",
        "lat": "41n26",
        "lon": "174w30",
        "gpsLat": -41.433333,
        "gpsLon": 174.5,
        "hsys": 1,
        "tradition": False,
        "predictive": True,
        "zodiacal": 0,
        "simpleAsp": False,
        "strongRecption": False,
        "virtualPointReceiveAsp": True,
        "southchart": False,
        "ad": 1,
        "name": "Horosa Smoke",
        "pos": "Wellington",
    }
    east_birth = {
        "date": "2028-04-06",
        "time": "09:33:00",
        "zone": "+08:00",
        "lat": "31n13",
        "lon": "121e28",
        "gpsLat": 31.2167,
        "gpsLon": 121.4667,
        "ad": 1,
    }
    return {
        "export_registry": {"technique": "qimen"},
        "export_parse": {
            "technique": "qimen",
            "content": (
                "[起盘信息]\n日期：2028-04-06 09:33:00\n\n"
                "[八宫]\n坎一宫：值符=天蓬；值使=休门\n\n"
                "[演卦]\n值符值使演卦：天泽履之乾为天\n"
            ),
            "selected_sections": ["起盘信息", "八宫详解", "奇门演卦"],
        },
        "qimen": dict(east_birth),
        "taiyi": dict(east_birth),
        "jinkou": {**east_birth, "diFen": "酉", "guirengType": 0},
        "suzhan": {**base_birth, "szchart": 0, "szshape": 0, "houseStartMode": 1, "doubingSu28": True},
        "sixyao": {
            "date": "2028-04-06",
            "time": "09:33:00",
            "zone": "+08:00",
            "lat": "31n13",
            "lon": "121e28",
            "gpsLat": 31.2167,
            "gpsLon": 121.4667,
            "question": "测试六爻输出",
            "gua_code": "111111",
            "changed_code": "101010",
            "lines": [
                {"value": 1, "change": False, "god": "青龙", "name": "初爻"},
                {"value": 1, "change": False, "god": "朱雀", "name": "二爻"},
                {"value": 1, "change": True, "god": "勾陈", "name": "三爻"},
                {"value": 1, "change": False, "god": "腾蛇", "name": "四爻"},
                {"value": 1, "change": False, "god": "白虎", "name": "五爻"},
                {"value": 1, "change": True, "god": "玄武", "name": "上爻"},
            ],
        },
        "tongshefa": {"taiyin": "巽", "taiyang": "坤", "shaoyang": "震", "shaoyin": "震"},
        "sanshiunited": dict(east_birth),
        "chart": dict(base_birth),
        "chart13": {**base_birth, "predictive": 0},
        "hellen_chart": {**base_birth, "predictive": 0},
        "guolao_chart": {
            "date": "2028/04/06",
            "time": "09:33:00",
            "zone": "+08:00",
            "lat": "31n13",
            "lon": "121e28",
            "gpsLat": 31.2167,
            "gpsLon": 121.4667,
            "hsys": 0,
            "tradition": True,
            "zodiacal": 0,
            "doubingSu28": True,
            "predictive": False,
            "ad": 1,
        },
        "germany": {**base_birth, "predictive": False},
        "solarreturn": {**base_birth, "datetime": "2031-04-06 09:33:00", "dirZone": "+08:00", "dirLat": "31n13", "dirLon": "121e28"},
        "lunarreturn": {**base_birth, "datetime": "2031-04-06 09:33:00", "dirZone": "+08:00", "dirLat": "31n13", "dirLon": "121e28"},
        "solararc": {**base_birth, "datetime": "2031-04-06 09:33:00", "dirZone": "+00:00"},
        "givenyear": {**base_birth, "datetime": "2031-04-06 09:33:00", "dirZone": "+08:00", "dirLat": "31n13", "dirLon": "121e28"},
        "profection": {**base_birth, "datetime": "2031-04-06 09:33:00", "dirZone": "+00:00"},
        "pd": {**base_birth, "pdtype": 0, "pdMethod": "astroapp_alchabitius", "pdTimeKey": "Ptolemy", "pdaspects": [0, 60, 90, 120, 180]},
        "pdchart": {**base_birth, "pdtype": 0, "pdMethod": "astroapp_alchabitius", "pdTimeKey": "Ptolemy", "showPdBounds": 1, "datetime": "2031-04-06 09:33:00", "dirZone": "+00:00"},
        "zr": dict(base_birth),
        "firdaria": dict(base_birth),
        "decennials": {**base_birth, "startMode": "sect_light", "orderType": "zodiacal", "dayMethod": "valens", "calendarType": "calendar_360", "aiMode": "l1_all"},
        "otherbu": {**base_birth, "question": "测试占星骰子", "planet": "Sun", "sign": "Aries", "house": 2},
        "relative": {
            "inner": {**base_birth, "name": "甲"},
            "outer": {**base_birth, "date": "1992/03/02", "time": "08:18:00", "name": "乙"},
            "hsys": 0,
            "zodiacal": 0,
            "relative": 0,
        },
        "india_chart": {**base_birth, "zodiacal": 1, "predictive": 1, "pdtype": 0, "pdMethod": "astroapp_alchabitius", "pdTimeKey": "Ptolemy", "pdaspects": [0, 60, 90, 120, 180]},
        "ziwei_birth": {**east_birth, "gender": True, "timeAlg": 0},
        "ziwei_rules": {},
        "bazi_birth": dict(east_birth),
        "bazi_direct": {**east_birth, "gender": True, "timeAlg": 0, "after23NewDay": 0, "adjustJieqi": False, "byLon": False, "phaseType": 0},
        "liureng_gods": {**east_birth, "after23NewDay": False},
        "liureng_runyear": {
            **east_birth,
            "date": "2020-04-06",
            "gender": True,
            "guaDate": "2028-04-06",
            "guaTime": "09:33:00",
            "guaZone": "+08:00",
            "guaLat": "31n13",
            "guaLon": "121e28",
            "guaAd": 1,
            "guaAfter23NewDay": False,
        },
        "jieqi_year": {
            "year": 2028,
            "zone": "+08:00",
            "lat": "31n13",
            "lon": "121e28",
            "gpsLat": 31.2167,
            "gpsLon": 121.4667,
            "hsys": 1,
            "zodiacal": 0,
            "doubingSu28": False,
            "jieqis": ["春分", "夏至", "秋分", "冬至"],
            "ad": 1,
        },
        "nongli_time": {
            "date": "2028-04-06",
            "time": "09:33:00",
            "zone": "+08:00",
            "lat": "31n13",
            "lon": "121e28",
            "gpsLat": 31.2167,
            "gpsLon": 121.4667,
            "gender": True,
            "after23NewDay": 0,
            "timeAlg": 0,
            "ad": 1,
        },
        "gua_desc": {"name": ["111111", "000000", "101010"]},
        "gua_meiyi": {"name": ["111", "000"]},
    }
